--[[
SARHA Android Remote Home Automation

This eLua script is auto-generated by the SARHA-App

Info
Name: NewStateMachine
Create ID: 1339594906
Change ID: 1339594906
]]--

module(..., package.seeall)

local tstartV0

function state0()
	coroutine.yield()
	if ((kit.IO.DI0.merge==0) and (kit.IO.DI1.merge==0)) then
			kit.IO.AO0.real=29
			return state1()
	elseif false then
			return state2()
	else
		return state0()
	end
end

function state1()
	coroutine.yield()
	if (kit.IO.DI3.merge==0) then
			kit.IO.AO0.real=96
			return state0()
	else
		return state1()
	end
end

function state2()
	coroutine.yield()
end

function state3()
	coroutine.yield()
end

function state4()
	coroutine.yield()
end



table.insert(threads, coroutine.create(function ()
	state0()
end))
